### ISSUE TITLE
 GtkDialog mapped without a transient parent. This is discouraged.

### ISSUE THREAD

**Issue by zeidk** [mackorone/mms#6] opened 2019-11-18 20:39 UTC
Hello,
when clicking on the folder icon to load a maze file we have the message " GtkDialog mapped without a transient parent. This is discouraged." This looks like a warning but it will freeze the application. Is there anything we can add in the code to prevent the simulator to freeze upon opening a maze file?

Also, one alternative is to edit the history of mazes already opened (see attached picture) 
![mms-issue](https://user-images.githubusercontent.com/8428984/69092566-aad90c00-0a1a-11ea-963d-9359244ae6e4.png)
and select one from there instead of clicking the folder icon. Where is this file stored on the machine?

Thanks

**Comment by mackorone** [comment] 2019-11-19 06:40
> GtkDialog mapped without a transient parent.

Interesting, I haven't seen that error before. If it causes the simulator to freeze, it's definitely worth fixing. My hunch is that it has something to do with how we create the file dialog ([code](https://github.com/mackorone/mms/blob/master/src/Window.cpp#L329)).

If you don't mind me asking, what platform/OS are you using? Also, are you using one of the pre-built binaries, or are you building and running from source?



> Where is this file stored on the machine?

All settings, including the list of maze files, are stored using the [`QSettings`](https://doc.qt.io/qt-5/qsettings.html) class. The location of the config depends on the OS - for linux, I think it's `~/.config/mackorone/mms.conf` ([documentation](https://doc.qt.io/qt-5/qsettings.html#platform-specific-notes)).

**Comment by zeidk** [comment] 2019-11-19 15:04
Hello, I wrote on the behalf of someone who is having this issue and I will ask him to join the discussion. He is using Ubuntu 18.04 (virtual machine) and he built it from source.

We don't know much about QT but as an alternative, we would like to hardcode the path to a maze file in the mms code (not using the load maze function). Do you mind pointing to the location in the code where we can include this?

Thank you,

**Comment by mackorone** [comment] 2019-11-19 17:18
> He is using Ubuntu 18.04 (virtual machine) and he built it from source.

Thanks for the info, I'll try to reproduce the error later this week.

>  Do you mind pointing to the location in the code where we can include this?

Sure, just hardcode the path here: https://github.com/mackorone/mms/blob/master/src/Window.cpp#L278

**Comment by zeidk** [comment] 2019-11-19 17:32
Awesome, thank you.

zeid

**Comment by sully892** [comment] 2019-11-21 02:36
Hello, Mack. I am the person zeidk is referring to. Since the last time I deleted the mms repo locally, and re-cloned it everything seems to be working. Not sure what happened to mess everything up in the first place...not sure if you still wanted to pursue this issue on your own, but it might be a witch hunt...thanks

**Comment by mackorone** [comment] 2019-11-22 06:40
Great, happy to hear everything is working! I'm going to close this for now, but don't hesitate to let me know if you run into any other issues.

**Closed by mackorone** 2019-11-22 06:40 UTC
